### PR TITLE
Setup all api calls to use credentials in case hop stuff needs to be …

### PR DESCRIPTION
**Pull request by jnation3406**
…refreshed or logged out, and setup all calls to catch a 401 and trigger UI logout

This goes along with the hermes PR. The behavior now is that if your oidc credentials expire, the next api call that recieves the 401 back will trigger your UI to visibly logout (say Hermes-Guest again), and reload the page you are on. I think this is the safest thing to do if a user has their oidc creds expire, and then they can login again if they want. Since we are setting the timeout to a long time (2 weeks), this shouldn't happen often.

### CODE REVIEW

**Review by phycodurus — APPROVED** [review]

**Comment by jchate6** [comment]
So, I am not sure this is related, but currently I have the issue that I cannot "log out" of CILogon. 
If I sign into google with one account, I cannot then sign into it with another account from the same browser. 
I assume I could clear my cookies to do this, but normally I just wait a little while and it's fixed. Will setting a 2 week timeout basically make this impossible?

**Comment by jchate6** [comment]
As it stands the logout button doesn't really log you out of Hermes in the secure way I'd expect from a logout button. If you were using someone else's computer or a public terminal, anyone who came after you would not only be able to log into your Hermes account, but in fact, not have a choice in the matter.

**Comment by jnation3406** [comment]
> As it stands the logout button doesn't really log you out of Hermes in the secure way I'd expect from a logout button. If you were using someone else's computer or a public terminal, anyone who came after you would not only be able to log into your Hermes account, but in fact, not have a choice in the matter.

Yeah I'm not sure exactly how this works but I assume its a CILogin cookie in your browser, so an incognito window should stop it... We aren't saving anything in the hermes backend or anything to cause the simple re-login...

**Comment by jchate6** [comment]
So, I cleared my Scimma Cookies and now when I log in from Hermes it doesn't show my username at the top... :(

**Pull request merged**
